# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build] # Make sure you don’t have a duplicate [build] context!
  functions = "functions/"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[headers]]
  for = "functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
